### ISSUE TITLE
Ubuntu stand (and maybe others) not being synced 

### ISSUE THREAD

**Issue by pedropintosilva** [FOSDEM/stands-website#183]
Yesterday I found out that latest changes on the ubuntu stand repositories were not being visible after one day (cron job). I have inspected and I do not see any problem with the last changes from that side and the branch name etc didn't suffer any changes.

I don't know what it could be the problem. But I do get an error in one of the other submodules:

1. `git clone git@github.com:FOSDEM/stands-website.git`
2. `git submodule init`
3. `git submodule update`

```bash
fatal: remote error: want a94604f3b0d2c59ce41e56e97dfb0a7430c00009 not valid
fatal: Fetched in submodule path 'content/stands/libreoffice', but it did not contain a94604f3b0d2c59ce41e56e97dfb0a7430c00009. Direct fetching of that commit failed.
```

**Comment by tcarreira** [comment]
indeed, the cron does not seem to be working. 


But... 
That error is because the main repo is pointing to a particular submodule commit that does not exist anymore.

It will go away if you update submodules directly before initing them, meaning

```
git clone git@github.com:FOSDEM/stands-website.git

git submodule update --init --remote
```
Like https://github.com/FOSDEM/stands-website/blob/d59dd36cb5745e4f19f17bafb93e8e9f2dec2bb5/.github/workflows/build-on-pr.yml#L16

**Comment by pieterdp** [comment]
Hello,

I did some things and now everything is working again!

Pieter
